/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import fiestel.cipher.FiestelCipher;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author Gayan Sandaruwan
 */
public class MainInterface extends javax.swing.JFrame {

    private JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
    private File plainFile;
    private String plainFileName;
    private String plainFilePath;
    private String encryptedFile;
    private String encryptedFileName;

    /**
     * Creates new form MainInterface
     */
    public MainInterface() {

        initComponents();
//        roundsCountEn = new JComboBox<>();
//        String [] integerList   =    new String[50];
        roundsCountEn.removeAllItems();
        for (int i = 0; i < 50; i++) {
//            integerList[i] = String.valueOf(i+1);
            roundsCountEn.addItem(String.valueOf(i + 1));
        }
        roundsCountEn.setSelectedIndex(1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sectionLabelDe = new javax.swing.JLabel();
        sectionLabelEn = new javax.swing.JLabel();
        encryptionKey = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        filePathEn = new javax.swing.JTextField();
        chooseFileEn = new javax.swing.JButton();
        roundsEnLabel = new javax.swing.JLabel();
        roundsCountEn = new javax.swing.JComboBox<>();
        encryptionKeyAlert = new javax.swing.JLabel();
        filePathAlert = new javax.swing.JLabel();
        chooseFileDe = new javax.swing.JButton();
        roundsDeLabel = new javax.swing.JLabel();
        roundsCoundDe = new javax.swing.JComboBox<>();
        decryptionKeyAlert = new javax.swing.JLabel();
        filePathAlertDe = new javax.swing.JLabel();
        decryptionKey = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        filePathDe = new javax.swing.JTextField();
        encryptBtn = new javax.swing.JButton();
        decryotBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sectionLabelDe.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        sectionLabelDe.setText("Decrypt Section");

        sectionLabelEn.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        sectionLabelEn.setText("Encrypt Section");

        encryptionKey.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                encryptionKeyKeyTyped(evt);
            }
        });

        jLabel1.setText("8 digit Encryption Key");

        filePathEn.setText("Path to the file");
        filePathEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filePathEnActionPerformed(evt);
            }
        });

        chooseFileEn.setText("Choose File");
        chooseFileEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFileEnActionPerformed(evt);
            }
        });

        roundsEnLabel.setText("Encryption Rounds");

        roundsCountEn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        encryptionKeyAlert.setText("Enter key");

        filePathAlert.setText("file path");

        chooseFileDe.setText("Choose File");

        roundsDeLabel.setText("Decryption Rounds");

        roundsCoundDe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        decryptionKeyAlert.setText("Enter key");

        filePathAlertDe.setText("file path");

        decryptionKey.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                decryptionKeyKeyTyped(evt);
            }
        });

        jLabel4.setText("8 digit Dncryption Key");

        filePathDe.setText("Path to the file");
        filePathDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filePathDeActionPerformed(evt);
            }
        });

        encryptBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        encryptBtn.setText("Encrypt");
        encryptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encryptBtnActionPerformed(evt);
            }
        });

        decryotBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        decryotBtn.setText("Decrypt");

        jLabel2.setText("Fiestel Network with ASCII representation");

        jLabel3.setText("© 2017 GayanSandaruwan");

        jLabel5.setText("Higher Number of Rounds of Encryption might cost more Time.");

        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(chooseFileEn)
                                            .addComponent(roundsEnLabel))
                                        .addGap(24, 24, 24)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(roundsCountEn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(encryptBtn)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(filePathEn)
                                                        .addComponent(encryptionKey))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(encryptionKeyAlert)
                                                        .addComponent(filePathAlert))))))
                                    .addComponent(sectionLabelEn, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(chooseFileDe)
                                    .addComponent(roundsDeLabel))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(roundsCoundDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(filePathDe)
                                            .addComponent(decryptionKey, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(decryptionKeyAlert)
                                            .addComponent(filePathAlertDe)))
                                    .addComponent(decryotBtn)))
                            .addComponent(sectionLabelDe, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 41, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sectionLabelEn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sectionLabelDe, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(encryptionKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(encryptionKeyAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(filePathEn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chooseFileEn)
                                    .addComponent(filePathAlert))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(roundsEnLabel)
                                    .addComponent(roundsCountEn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(decryptionKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(decryptionKeyAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(filePathDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chooseFileDe)
                                    .addComponent(filePathAlertDe))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(roundsDeLabel)
                                    .addComponent(roundsCoundDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(encryptBtn)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(decryotBtn)
                                .addGap(25, 25, 25))))
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filePathEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filePathEnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filePathEnActionPerformed

    private void filePathDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filePathDeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filePathDeActionPerformed

    private void encryptionKeyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_encryptionKeyKeyTyped
        // TODO add your handling code here:
        String text = encryptionKey.getText();
//        if()
        if (text.length() == 7) {
            encryptionKeyAlert.setText("Good!");
        } else if (text.length() < 7) {
            encryptionKeyAlert.setText(text.length() + 1 + "/8");
        } else {
            encryptionKeyAlert.setText("Error! More than 8");
        }
    }//GEN-LAST:event_encryptionKeyKeyTyped

    private void decryptionKeyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_decryptionKeyKeyTyped
        String text = decryptionKey.getText();
//        if()
        if (text.length() == 7) {
            decryptionKeyAlert.setText("Good!");
        } else if (text.length() < 7) {
            decryptionKeyAlert.setText(text.length() + 1 + "/8");
        } else {
            decryptionKeyAlert.setText("Error! More than 8");
        }
    }//GEN-LAST:event_decryptionKeyKeyTyped

    private void chooseFileEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseFileEnActionPerformed

        int returnValue = jfc.showOpenDialog(null);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            this.plainFile = jfc.getSelectedFile();
            this.plainFilePath = this.plainFile.getAbsolutePath();
            System.out.println(this.plainFilePath);
            this.plainFileName = this.plainFile.getName();

            this.filePathEn.setText(plainFilePath + "/" + this.plainFileName);
            this.filePathAlert.setText("Good");
        } else {
            this.plainFile = null;
        }
//        String text = readFile(plainFile);
//        String fileName = file.getName();
    }//GEN-LAST:event_chooseFileEnActionPerformed

    private void encryptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encryptBtnActionPerformed

        FiestelCipher cipher = new FiestelCipher();
        try {
            FileReader fs = new FileReader(plainFile);
            BufferedReader br = new BufferedReader(fs);
            long length = 0;
            String line;
            String text="";
            System.out.println("Reading File");
            while ((line = br.readLine()) != null) {
                text+=line;
                length += line.length();
            }
            System.out.println(line);
            int rounds = roundsCountEn.getSelectedIndex()+1;
            String key = encryptionKey.getText();
            System.out.println("Encryption Started");
            boolean encrypted=cipher.encrypt(rounds, key, text, this.plainFileName);
            if(encrypted){
                System.out.println("File Encryption Successfull Stored at"+plainFilePath+"\\"+plainFileName+"encrypted.txt");
            }
            
        } catch (Exception ex) {
            Logger.getLogger(MainInterface.class.getName()).log(Level.SEVERE, null, ex);
            filePathAlert.setText("Selected File Is Incorrect");
        }


    }//GEN-LAST:event_encryptBtnActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chooseFileDe;
    private javax.swing.JButton chooseFileEn;
    private javax.swing.JButton decryotBtn;
    private javax.swing.JPasswordField decryptionKey;
    private javax.swing.JLabel decryptionKeyAlert;
    private javax.swing.JButton encryptBtn;
    private javax.swing.JPasswordField encryptionKey;
    private javax.swing.JLabel encryptionKeyAlert;
    private javax.swing.JLabel filePathAlert;
    private javax.swing.JLabel filePathAlertDe;
    private javax.swing.JTextField filePathDe;
    private javax.swing.JTextField filePathEn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox<String> roundsCoundDe;
    private javax.swing.JComboBox<String> roundsCountEn;
    private javax.swing.JLabel roundsDeLabel;
    private javax.swing.JLabel roundsEnLabel;
    private javax.swing.JLabel sectionLabelDe;
    private javax.swing.JLabel sectionLabelEn;
    // End of variables declaration//GEN-END:variables
}
